//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squares.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public string message { get; set; }
        public int userID { get; set; }
        public int squareSetID { get; set; }
    
        public virtual squareSet squareSet { get; set; }
        public virtual user user { get; set; }
    }
}
