//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squares.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userRole_privileges
    {
        public int id { get; set; }
        public int roleID { get; set; }
        public int privilegeID { get; set; }
    
        public virtual privileges privileges { get; set; }
        public virtual userRole userRole { get; set; }
    }
}
